[package]
name = "som"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Somfic"]
description = "The 'som' programming language"
rust-version = "1.87.0"

[dependencies]
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
owo-colors = "4.2.3"
pretty_assertions = "1.4.1"
cranelift = "0.125.4"
cranelift-module = "0.125.1"
cranelift-jit = "0.125.4"
cranelift-native = "0.125.1"
memmap2 = "0.9.9"
clap = { version = "4.5.52", features = ["derive"] }
syn = "2.0.108"
quote = "1.0.42"
proc-macro2 = "1.0.103"
thiserror = "2.0.17"
nucleo-matcher = "0.3.1"
libc = "0.2.177"
clap-file = "0.2.0"
colored = "3.0.0"
notify = "8.2.0"
once_cell = "1.21.3"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "compilation_bench"
harness = false

[[bench]]
name = "execution_bench"
harness = false

[[bench]]
name = "end_to_end_bench"
harness = false
