[package]
name = "som"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Somfic"]
description = "The 'som' programming language"
rust-version = "1.89.0"

[dependencies]
cranelift = { version = "0.126.0", features = ["module", "object"] }
nerd-font-symbols = "0.3.0"
owo-colors = "4.2.3"
target-lexicon = "0.13.3"
thiserror = "2.0.17"
